// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkIfContactIsTaken = `-- name: CheckIfContactIsTaken :one
select
    exists (
        select 1
        from users
        where
            email = any($1::text[])
            or phone = any($1::text[])
    ) as contact_exists
`

func (q *Queries) CheckIfContactIsTaken(ctx context.Context, contacts []string) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfContactIsTaken, contacts)
	var contact_exists bool
	err := row.Scan(&contact_exists)
	return contact_exists, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO auth_sessions(
  user_id, 
  refresh_token_hash, 
  ip_address, 
  user_agent,
  expires_at
) VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	UserID           uuid.UUID
	RefreshTokenHash pgtype.Text
	IpAddress        *netip.Addr
	UserAgent        pgtype.Text
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO users(
  email, phone, full_name, password_hash
) VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, full_name, phone, is_email_verified, is_active, last_login_at, created_at, updated_at
`

type CreateUserAccountParams struct {
	Email        string
	Phone        pgtype.Text
	FullName     pgtype.Text
	PasswordHash string
}

func (q *Queries) CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserAccount,
		arg.Email,
		arg.Phone,
		arg.FullName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
delete from auth_sessions
where refresh_token_hash = $1 and user_id = $2
`

type DeleteRefreshTokenParams struct {
	RefreshTokenHash pgtype.Text
	UserID           uuid.UUID
}

func (q *Queries) DeleteRefreshToken(ctx context.Context, arg DeleteRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, arg.RefreshTokenHash, arg.UserID)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
select
    id,
    email,
    password_hash,
    full_name,
    phone,
    is_email_verified,
    is_active,
    last_login_at,
    created_at
from users
where email = $1
limit 1
`

type FindUserByEmailRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	FullName        pgtype.Text
	Phone           pgtype.Text
	IsEmailVerified pgtype.Bool
	IsActive        pgtype.Bool
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
select
    id,
    email,
    password_hash,
    full_name,
    phone,
    is_email_verified,
    is_active,
    last_login_at,
    created_at
from users
where id = $1
limit 1
`

type FindUserByIdRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	FullName        pgtype.Text
	Phone           pgtype.Text
	IsEmailVerified pgtype.Bool
	IsActive        pgtype.Bool
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (FindUserByIdRow, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i FindUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByPhone = `-- name: FindUserByPhone :one
select
    id,
    email,
    password_hash,
    full_name,
    phone,
    is_email_verified,
    is_active,
    last_login_at,
    created_at
from users
where phone = $1
limit 1
`

type FindUserByPhoneRow struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	FullName        pgtype.Text
	Phone           pgtype.Text
	IsEmailVerified pgtype.Bool
	IsActive        pgtype.Bool
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) FindUserByPhone(ctx context.Context, phone pgtype.Text) (FindUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, findUserByPhone, phone)
	var i FindUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.IsEmailVerified,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenForUser = `-- name: GetTokenForUser :one
select id, user_id, refresh_token_hash, ip_address, user_agent, expires_at, created_at, updated_at
from auth_sessions
where user_id = $1
limit 1
`

func (q *Queries) GetTokenForUser(ctx context.Context, userID uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getTokenForUser, userID)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailAsVerified = `-- name: MarkEmailAsVerified :exec
UPDATE users 
SET is_email_verified = true, is_active = true
WHERE id = $1
`

func (q *Queries) MarkEmailAsVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailAsVerified, id)
	return err
}

const recordLastLoginTime = `-- name: RecordLastLoginTime :exec
UPDATE users
SET last_login_at = now()
WHERE id = $1
`

func (q *Queries) RecordLastLoginTime(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordLastLoginTime, id)
	return err
}
