// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_integrations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBusinessIntegration = `-- name: CreateBusinessIntegration :one
INSERT INTO business_integrations (
  business_id,
  provider,
  environment
) VALUES (
  $1, $2, $3
)
RETURNING id, business_id, provider, environment, status, created_at, updated_at
`

type CreateBusinessIntegrationParams struct {
	BusinessID  uuid.UUID
	Provider    string
	Environment string
}

func (q *Queries) CreateBusinessIntegration(ctx context.Context, arg CreateBusinessIntegrationParams) (BusinessIntegration, error) {
	row := q.db.QueryRow(ctx, createBusinessIntegration, arg.BusinessID, arg.Provider, arg.Environment)
	var i BusinessIntegration
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Provider,
		&i.Environment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBusinessIntegration = `-- name: DeleteBusinessIntegration :exec
delete from business_integrations
where id = $1 and business_id = $2
`

type DeleteBusinessIntegrationParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) DeleteBusinessIntegration(ctx context.Context, arg DeleteBusinessIntegrationParams) error {
	_, err := q.db.Exec(ctx, deleteBusinessIntegration, arg.ID, arg.BusinessID)
	return err
}

const deleteIntegrationSecret = `-- name: DeleteIntegrationSecret :exec
delete from integration_secrets
where integration_id = $1 and key_name = $2
`

type DeleteIntegrationSecretParams struct {
	IntegrationID uuid.UUID
	KeyName       string
}

func (q *Queries) DeleteIntegrationSecret(ctx context.Context, arg DeleteIntegrationSecretParams) error {
	_, err := q.db.Exec(ctx, deleteIntegrationSecret, arg.IntegrationID, arg.KeyName)
	return err
}

const getBusinessIntegrationByID = `-- name: GetBusinessIntegrationByID :one
select id, business_id, provider, environment, status, created_at, updated_at
from business_integrations
where id = $1 and business_id = $2
`

type GetBusinessIntegrationByIDParams struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
}

func (q *Queries) GetBusinessIntegrationByID(ctx context.Context, arg GetBusinessIntegrationByIDParams) (BusinessIntegration, error) {
	row := q.db.QueryRow(ctx, getBusinessIntegrationByID, arg.ID, arg.BusinessID)
	var i BusinessIntegration
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Provider,
		&i.Environment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessIntegrationByProvider = `-- name: GetBusinessIntegrationByProvider :one
select id, business_id, provider, environment, status, created_at, updated_at
from business_integrations
where business_id = $1 and provider = $2 and environment = $3
`

type GetBusinessIntegrationByProviderParams struct {
	BusinessID  uuid.UUID
	Provider    string
	Environment string
}

func (q *Queries) GetBusinessIntegrationByProvider(ctx context.Context, arg GetBusinessIntegrationByProviderParams) (BusinessIntegration, error) {
	row := q.db.QueryRow(ctx, getBusinessIntegrationByProvider, arg.BusinessID, arg.Provider, arg.Environment)
	var i BusinessIntegration
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Provider,
		&i.Environment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationSecret = `-- name: GetIntegrationSecret :one
select encrypted_value
from integration_secrets
where integration_id = $1 and key_name = $2
`

type GetIntegrationSecretParams struct {
	IntegrationID uuid.UUID
	KeyName       string
}

func (q *Queries) GetIntegrationSecret(ctx context.Context, arg GetIntegrationSecretParams) (string, error) {
	row := q.db.QueryRow(ctx, getIntegrationSecret, arg.IntegrationID, arg.KeyName)
	var encrypted_value string
	err := row.Scan(&encrypted_value)
	return encrypted_value, err
}

const listBusinessIntegrations = `-- name: ListBusinessIntegrations :many
select id, business_id, provider, environment, status, created_at, updated_at
from business_integrations
where business_id = $1
order by created_at desc
`

func (q *Queries) ListBusinessIntegrations(ctx context.Context, businessID uuid.UUID) ([]BusinessIntegration, error) {
	rows, err := q.db.Query(ctx, listBusinessIntegrations, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessIntegration
	for rows.Next() {
		var i BusinessIntegration
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Provider,
			&i.Environment,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationSecrets = `-- name: ListIntegrationSecrets :many
select key_name, encrypted_value
from integration_secrets
where integration_id = $1
`

type ListIntegrationSecretsRow struct {
	KeyName        string
	EncryptedValue string
}

func (q *Queries) ListIntegrationSecrets(ctx context.Context, integrationID uuid.UUID) ([]ListIntegrationSecretsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationSecrets, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationSecretsRow
	for rows.Next() {
		var i ListIntegrationSecretsRow
		if err := rows.Scan(&i.KeyName, &i.EncryptedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusinessIntegrationEnvironment = `-- name: UpdateBusinessIntegrationEnvironment :one
UPDATE business_integrations
SET environment = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, business_id, provider, environment, status, created_at, updated_at
`

type UpdateBusinessIntegrationEnvironmentParams struct {
	ID          uuid.UUID
	Environment string
}

func (q *Queries) UpdateBusinessIntegrationEnvironment(ctx context.Context, arg UpdateBusinessIntegrationEnvironmentParams) (BusinessIntegration, error) {
	row := q.db.QueryRow(ctx, updateBusinessIntegrationEnvironment, arg.ID, arg.Environment)
	var i BusinessIntegration
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Provider,
		&i.Environment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBusinessIntegrationStatus = `-- name: UpdateBusinessIntegrationStatus :one
UPDATE business_integrations
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, business_id, provider, environment, status, created_at, updated_at
`

type UpdateBusinessIntegrationStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateBusinessIntegrationStatus(ctx context.Context, arg UpdateBusinessIntegrationStatusParams) (BusinessIntegration, error) {
	row := q.db.QueryRow(ctx, updateBusinessIntegrationStatus, arg.ID, arg.Status)
	var i BusinessIntegration
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Provider,
		&i.Environment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIntegrationSecret = `-- name: UpsertIntegrationSecret :one
INSERT INTO integration_secrets (
  integration_id,
  key_name,
  encrypted_value
) VALUES (
  $1, $2, $3
)
ON CONFLICT (integration_id, key_name)
DO UPDATE SET
  encrypted_value = EXCLUDED.encrypted_value,
  updated_at = now()
RETURNING id, integration_id, key_name, encrypted_value, created_at, updated_at
`

type UpsertIntegrationSecretParams struct {
	IntegrationID  uuid.UUID
	KeyName        string
	EncryptedValue string
}

// ---------------------
// Integration secrets
// ---------------------
func (q *Queries) UpsertIntegrationSecret(ctx context.Context, arg UpsertIntegrationSecretParams) (IntegrationSecret, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationSecret, arg.IntegrationID, arg.KeyName, arg.EncryptedValue)
	var i IntegrationSecret
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.KeyName,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
