// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: businesses.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToBusiness = `-- name: AddUserToBusiness :exec
INSERT INTO business_users (
  business_id,
  user_id,
  role
)
VALUES ($1, $2, $3)
`

type AddUserToBusinessParams struct {
	BusinessID uuid.NullUUID
	UserID     uuid.NullUUID
	Role       pgtype.Text
}

func (q *Queries) AddUserToBusiness(ctx context.Context, arg AddUserToBusinessParams) error {
	_, err := q.db.Exec(ctx, addUserToBusiness, arg.BusinessID, arg.UserID, arg.Role)
	return err
}

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (
  legal_name,
  trading_name,
  kra_pin,
  business_type,
  email,
  phone,
  country
)
VALUES (
  $1, $2, $3, $4, $5, $6, COALESCE($7, 'KE')
)
RETURNING id, legal_name, trading_name, kra_pin, business_type, email, phone, country, status, created_at, updated_at
`

type CreateBusinessParams struct {
	LegalName    string
	TradingName  pgtype.Text
	KraPin       string
	BusinessType pgtype.Text
	Email        pgtype.Text
	Phone        pgtype.Text
	Column7      interface{}
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness,
		arg.LegalName,
		arg.TradingName,
		arg.KraPin,
		arg.BusinessType,
		arg.Email,
		arg.Phone,
		arg.Column7,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradingName,
		&i.KraPin,
		&i.BusinessType,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBusinessKYC = `-- name: CreateBusinessKYC :one
INSERT INTO business_kyc (
  business_id,
  document_type,
  document_url,
  status
)
VALUES ($1, $2, $3, 'pending')
RETURNING id, business_id, document_type, document_url, status, status_text, verified_by, verified_at, created_at, updated_at
`

type CreateBusinessKYCParams struct {
	BusinessID   uuid.NullUUID
	DocumentType pgtype.Text
	DocumentUrl  pgtype.Text
}

func (q *Queries) CreateBusinessKYC(ctx context.Context, arg CreateBusinessKYCParams) (BusinessKyc, error) {
	row := q.db.QueryRow(ctx, createBusinessKYC, arg.BusinessID, arg.DocumentType, arg.DocumentUrl)
	var i BusinessKyc
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.DocumentType,
		&i.DocumentUrl,
		&i.Status,
		&i.StatusText,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBusiness = `-- name: DeleteBusiness :exec
delete from businesses
where id = $1
`

func (q *Queries) DeleteBusiness(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBusiness, id)
	return err
}

const getBusinessByID = `-- name: GetBusinessByID :one
select id, legal_name, trading_name, kra_pin, business_type, email, phone, country, status, created_at, updated_at
from businesses
where id = $1
`

func (q *Queries) GetBusinessByID(ctx context.Context, id uuid.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByID, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradingName,
		&i.KraPin,
		&i.BusinessType,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessByKRAPIN = `-- name: GetBusinessByKRAPIN :one
select id, legal_name, trading_name, kra_pin, business_type, email, phone, country, status, created_at, updated_at
from businesses
where kra_pin = $1
`

func (q *Queries) GetBusinessByKRAPIN(ctx context.Context, kraPin string) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByKRAPIN, kraPin)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradingName,
		&i.KraPin,
		&i.BusinessType,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessKYC = `-- name: GetBusinessKYC :many
select id, business_id, document_type, document_url, status, status_text, verified_by, verified_at, created_at, updated_at
from business_kyc
where business_id = $1
order by created_at desc
`

func (q *Queries) GetBusinessKYC(ctx context.Context, businessID uuid.NullUUID) ([]BusinessKyc, error) {
	rows, err := q.db.Query(ctx, getBusinessKYC, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessKyc
	for rows.Next() {
		var i BusinessKyc
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.DocumentType,
			&i.DocumentUrl,
			&i.Status,
			&i.StatusText,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBusinessRole = `-- name: GetUserBusinessRole :one
select role
from business_users
where business_id = $1 and user_id = $2 and is_active = true
`

type GetUserBusinessRoleParams struct {
	BusinessID uuid.NullUUID
	UserID     uuid.NullUUID
}

func (q *Queries) GetUserBusinessRole(ctx context.Context, arg GetUserBusinessRoleParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserBusinessRole, arg.BusinessID, arg.UserID)
	var role pgtype.Text
	err := row.Scan(&role)
	return role, err
}

const hasVerifiedKYC = `-- name: HasVerifiedKYC :one
select
    exists (
        select 1 from business_kyc where business_id = $1 and status = 'verified'
    ) as has_verified
`

func (q *Queries) HasVerifiedKYC(ctx context.Context, businessID uuid.NullUUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasVerifiedKYC, businessID)
	var has_verified bool
	err := row.Scan(&has_verified)
	return has_verified, err
}

const listBusinessesByStatus = `-- name: ListBusinessesByStatus :many
select id, legal_name, trading_name, kra_pin, business_type, email, phone, country, status, created_at, updated_at
from businesses
where status = $1
order by created_at desc
`

func (q *Queries) ListBusinessesByStatus(ctx context.Context, status interface{}) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinessesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.LegalName,
			&i.TradingName,
			&i.KraPin,
			&i.BusinessType,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessesForUser = `-- name: ListBusinessesForUser :many
select b.id, b.legal_name, b.trading_name, b.kra_pin, b.business_type, b.email, b.phone, b.country, b.status, b.created_at, b.updated_at
from businesses b
join business_users bu on bu.business_id = b.id
where bu.user_id = $1 and bu.is_active = true
order by b.created_at desc
`

func (q *Queries) ListBusinessesForUser(ctx context.Context, userID uuid.NullUUID) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinessesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.LegalName,
			&i.TradingName,
			&i.KraPin,
			&i.BusinessType,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusinessContact = `-- name: UpdateBusinessContact :exec
UPDATE businesses
SET email = $2,
    phone = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateBusinessContactParams struct {
	ID    uuid.UUID
	Email pgtype.Text
	Phone pgtype.Text
}

func (q *Queries) UpdateBusinessContact(ctx context.Context, arg UpdateBusinessContactParams) error {
	_, err := q.db.Exec(ctx, updateBusinessContact, arg.ID, arg.Email, arg.Phone)
	return err
}

const updateBusinessDetails = `-- name: UpdateBusinessDetails :exec
UPDATE businesses
SET legal_name   = $2,
    trading_name = $3,
    business_type = $4,
    updated_at   = now()
WHERE id = $1
`

type UpdateBusinessDetailsParams struct {
	ID           uuid.UUID
	LegalName    string
	TradingName  pgtype.Text
	BusinessType pgtype.Text
}

func (q *Queries) UpdateBusinessDetails(ctx context.Context, arg UpdateBusinessDetailsParams) error {
	_, err := q.db.Exec(ctx, updateBusinessDetails,
		arg.ID,
		arg.LegalName,
		arg.TradingName,
		arg.BusinessType,
	)
	return err
}

const updateBusinessStatus = `-- name: UpdateBusinessStatus :exec
UPDATE businesses
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateBusinessStatusParams struct {
	ID     uuid.UUID
	Status interface{}
}

func (q *Queries) UpdateBusinessStatus(ctx context.Context, arg UpdateBusinessStatusParams) error {
	_, err := q.db.Exec(ctx, updateBusinessStatus, arg.ID, arg.Status)
	return err
}

const updateKYCStatus = `-- name: UpdateKYCStatus :exec
UPDATE business_kyc
SET status = $2,
    verified_by = $3,
    verified_at = now()
WHERE id = $1
`

type UpdateKYCStatusParams struct {
	ID         uuid.UUID
	Status     interface{}
	VerifiedBy uuid.NullUUID
}

func (q *Queries) UpdateKYCStatus(ctx context.Context, arg UpdateKYCStatusParams) error {
	_, err := q.db.Exec(ctx, updateKYCStatus, arg.ID, arg.Status, arg.VerifiedBy)
	return err
}
