// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForAddLineInvoiceLineItem implements pgx.CopyFromSource.
type iteratorForAddLineInvoiceLineItem struct {
	rows                 []AddLineInvoiceLineItemParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddLineInvoiceLineItem) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddLineInvoiceLineItem) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].InvoiceID,
		r.rows[0].Description,
		r.rows[0].Quantity,
		r.rows[0].UnitPrice,
		r.rows[0].VatRate,
		r.rows[0].VatAmount,
		r.rows[0].LineTotal,
	}, nil
}

func (r iteratorForAddLineInvoiceLineItem) Err() error {
	return nil
}

func (q *Queries) AddLineInvoiceLineItem(ctx context.Context, arg []AddLineInvoiceLineItemParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"invoice_items"}, []string{"invoice_id", "description", "quantity", "unit_price", "vat_rate", "vat_amount", "line_total"}, &iteratorForAddLineInvoiceLineItem{rows: arg})
}
