// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoies.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addLineInvoiceLineItem = `-- name: AddLineInvoiceLineItem :exec
INSERT INTO invoice_items (
  invoice_id, description, quantity, unit_price, vat_rate, vat_amount, line_total
) VALUES($1, $2, $3, $4, $5, $6, $7)
`

type AddLineInvoiceLineItemParams struct {
	InvoiceID   uuid.UUID
	Description pgtype.Text
	Quantity    pgtype.Numeric
	UnitPrice   pgtype.Numeric
	VatRate     pgtype.Numeric
	VatAmount   pgtype.Numeric
	LineTotal   pgtype.Numeric
}

func (q *Queries) AddLineInvoiceLineItem(ctx context.Context, arg AddLineInvoiceLineItemParams) error {
	_, err := q.db.Exec(ctx, addLineInvoiceLineItem,
		arg.InvoiceID,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.VatRate,
		arg.VatAmount,
		arg.LineTotal,
	)
	return err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices(
  business_id, invoice_number, seller_pin, buyer_pin, subtotal, vat_total, total
) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, business_id, invoice_number, seller_pin, buyer_pin, currency, subtotal, vat_total, total, status, kra_invoice_id, kra_receipt_url, issued_at, created_by, created_at, updated_at
`

type CreateInvoiceParams struct {
	BusinessID    uuid.UUID
	InvoiceNumber string
	SellerPin     string
	BuyerPin      pgtype.Text
	Subtotal      pgtype.Numeric
	VatTotal      pgtype.Numeric
	Total         pgtype.Numeric
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.BusinessID,
		arg.InvoiceNumber,
		arg.SellerPin,
		arg.BuyerPin,
		arg.Subtotal,
		arg.VatTotal,
		arg.Total,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.InvoiceNumber,
		&i.SellerPin,
		&i.BuyerPin,
		&i.Currency,
		&i.Subtotal,
		&i.VatTotal,
		&i.Total,
		&i.Status,
		&i.KraInvoiceID,
		&i.KraReceiptUrl,
		&i.IssuedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :exec
UPDATE invoices
SET status = $1, updated_at = now()
WHERE business_id = $2 AND id = $3
`

type UpdateInvoiceStatusParams struct {
	Status     string
	BusinessID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceStatus, arg.Status, arg.BusinessID, arg.ID)
	return err
}

const updateInvoiceTotals = `-- name: UpdateInvoiceTotals :exec
UPDATE invoices
SET subtotal = $1, vat_total = $2, total = $3, updated_at = now()
WHERE business_id = $4 AND id = $5
`

type UpdateInvoiceTotalsParams struct {
	Subtotal   pgtype.Numeric
	VatTotal   pgtype.Numeric
	Total      pgtype.Numeric
	BusinessID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateInvoiceTotals(ctx context.Context, arg UpdateInvoiceTotalsParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceTotals,
		arg.Subtotal,
		arg.VatTotal,
		arg.Total,
		arg.BusinessID,
		arg.ID,
	)
	return err
}

const updateInvoiceWithKraDetails = `-- name: UpdateInvoiceWithKraDetails :exec
UPDATE invoices
SET kra_invoice_id = $1, kra_receipt_url = $1, updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateInvoiceWithKraDetails(ctx context.Context, kraInvoiceID pgtype.Text) error {
	_, err := q.db.Exec(ctx, updateInvoiceWithKraDetails, kraInvoiceID)
	return err
}
