// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash pgtype.Text
	IpAddress        *netip.Addr
	UserAgent        pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Business struct {
	ID           uuid.UUID
	LegalName    string
	TradingName  pgtype.Text
	KraPin       string
	BusinessType pgtype.Text
	Email        pgtype.Text
	Phone        pgtype.Text
	Country      pgtype.Text
	Status       interface{}
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type BusinessIntegration struct {
	ID          uuid.UUID
	BusinessID  uuid.UUID
	Provider    string
	Environment string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type BusinessKyc struct {
	ID           uuid.UUID
	BusinessID   uuid.UUID
	DocumentType pgtype.Text
	DocumentUrl  pgtype.Text
	Status       interface{}
	StatusText   pgtype.Text
	VerifiedBy   uuid.NullUUID
	VerifiedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type BusinessUser struct {
	ID         uuid.UUID
	BusinessID uuid.UUID
	UserID     uuid.UUID
	Role       pgtype.Text
	IsActive   pgtype.Bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type IntegrationSecret struct {
	ID             uuid.UUID
	IntegrationID  uuid.UUID
	KeyName        string
	EncryptedValue string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Invoice struct {
	ID            uuid.UUID
	BusinessID    uuid.UUID
	InvoiceNumber string
	SellerPin     string
	BuyerPin      pgtype.Text
	Currency      pgtype.Text
	Subtotal      pgtype.Numeric
	VatTotal      pgtype.Numeric
	Total         pgtype.Numeric
	Status        string
	KraInvoiceID  pgtype.Text
	KraReceiptUrl pgtype.Text
	IssuedAt      pgtype.Timestamptz
	CreatedBy     uuid.NullUUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type InvoiceItem struct {
	ID          uuid.UUID
	InvoiceID   uuid.UUID
	Description pgtype.Text
	Quantity    pgtype.Numeric
	UnitPrice   pgtype.Numeric
	VatRate     pgtype.Numeric
	VatAmount   pgtype.Numeric
	LineTotal   pgtype.Numeric
}

type OutboxEvent struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	Status        string
	RetryCount    int32
	LastError     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	FullName        pgtype.Text
	Phone           pgtype.Text
	IsEmailVerified pgtype.Bool
	IsActive        pgtype.Bool
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Verification struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	VerificationType interface{}
	VerificationCode string
	CreatedAt        pgtype.Timestamptz
}
