// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Businessstatus string

const (
	BusinessstatusPending   Businessstatus = "pending"
	BusinessstatusActive    Businessstatus = "active"
	BusinessstatusSuspended Businessstatus = "suspended"
)

func (e *Businessstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Businessstatus(s)
	case string:
		*e = Businessstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Businessstatus: %T", src)
	}
	return nil
}

type NullBusinessstatus struct {
	Businessstatus Businessstatus
	Valid          bool // Valid is true if Businessstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Businessstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Businessstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Businessstatus), nil
}

type Documentstatus string

const (
	DocumentstatusPending  Documentstatus = "pending"
	DocumentstatusVerified Documentstatus = "verified"
	DocumentstatusRejected Documentstatus = "rejected"
)

func (e *Documentstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Documentstatus(s)
	case string:
		*e = Documentstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Documentstatus: %T", src)
	}
	return nil
}

type NullDocumentstatus struct {
	Documentstatus Documentstatus
	Valid          bool // Valid is true if Documentstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Documentstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Documentstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Documentstatus), nil
}

type AuthSession struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash pgtype.Text
	IpAddress        *netip.Addr
	UserAgent        pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type Business struct {
	ID           uuid.UUID
	LegalName    string
	TradingName  pgtype.Text
	KraPin       string
	BusinessType pgtype.Text
	Email        pgtype.Text
	Phone        pgtype.Text
	Country      pgtype.Text
	Status       NullBusinessstatus
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type BusinessKyc struct {
	ID           uuid.UUID
	BusinessID   uuid.NullUUID
	DocumentType pgtype.Text
	DocumentUrl  pgtype.Text
	Status       NullDocumentstatus
	StatusText   pgtype.Text
	VerifiedBy   uuid.NullUUID
	VerifiedAt   pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
}

type BusinessUser struct {
	ID         uuid.UUID
	BusinessID uuid.NullUUID
	UserID     uuid.NullUUID
	Role       pgtype.Text
	IsActive   pgtype.Bool
	CreatedAt  pgtype.Timestamptz
}

type OutboxEvent struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	Status        string
	RetryCount    int32
	LastError     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
}

type User struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	FullName        pgtype.Text
	Phone           pgtype.Text
	IsEmailVerified pgtype.Bool
	IsActive        pgtype.Bool
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
