// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Waitliststatus string

const (
	WaitliststatusPending    Waitliststatus = "pending"
	WaitliststatusInvited    Waitliststatus = "invited"
	WaitliststatusRegistered Waitliststatus = "registered"
)

func (e *Waitliststatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Waitliststatus(s)
	case string:
		*e = Waitliststatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Waitliststatus: %T", src)
	}
	return nil
}

type NullWaitliststatus struct {
	Waitliststatus Waitliststatus
	Valid          bool // Valid is true if Waitliststatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWaitliststatus) Scan(value interface{}) error {
	if value == nil {
		ns.Waitliststatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Waitliststatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWaitliststatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Waitliststatus), nil
}

type OutboxEvent struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	Status        string
	RetryCount    int32
	LastError     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
}

type Waitlist struct {
	ID        uuid.UUID
	Email     string
	Source    pgtype.Text
	Status    NullWaitliststatus
	CreatedAt pgtype.Timestamptz
}
