// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (
    aggregate_type,
    aggregate_id,
    event_type,
    payload
) VALUES (
    $1, $2, $3, $4
)
`

type CreateOutboxEventParams struct {
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const fetchPendingOutboxEvents = `-- name: FetchPendingOutboxEvents :many
select id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, last_error, created_at, processed_at
from outbox_events
where status = 'pending'
order by created_at
limit $1
for update skip locked
`

func (q *Queries) FetchPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, fetchPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchStuckOutboxEvents = `-- name: FetchStuckOutboxEvents :many
select id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, last_error, created_at, processed_at
from outbox_events
where status = 'processing' and created_at < now() - interval '10 minutes'
limit $1
`

func (q *Queries) FetchStuckOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, fetchStuckOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventDead = `-- name: MarkOutboxEventDead :exec
UPDATE outbox_events
SET
    status = 'failed',
    last_error = $2
WHERE id = $1
`

type MarkOutboxEventDeadParams struct {
	ID        uuid.UUID
	LastError pgtype.Text
}

func (q *Queries) MarkOutboxEventDead(ctx context.Context, arg MarkOutboxEventDeadParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventDead, arg.ID, arg.LastError)
	return err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET
    status = 'pending',
    retry_count = retry_count + 1,
    last_error = $2
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID        uuid.UUID
	LastError pgtype.Text
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events
SET
    status = 'processed',
    processed_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}

const markOutboxEventProcessing = `-- name: MarkOutboxEventProcessing :exec
UPDATE outbox_events
SET status = 'processing'
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessing, id)
	return err
}
