// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getVerifiationByCodeForUser = `-- name: GetVerifiationByCodeForUser :one
select id, user_id, verification_type, verification_code, created_at
from verifications
where user_id = $1 and verification_code = $2
limit 1
`

type GetVerifiationByCodeForUserParams struct {
	UserID           uuid.UUID
	VerificationCode string
}

func (q *Queries) GetVerifiationByCodeForUser(ctx context.Context, arg GetVerifiationByCodeForUserParams) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerifiationByCodeForUser, arg.UserID, arg.VerificationCode)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VerificationType,
		&i.VerificationCode,
		&i.CreatedAt,
	)
	return i, err
}

const markVerificationCodeAsConsumed = `-- name: MarkVerificationCodeAsConsumed :exec
delete from verifications
where id = $1
`

func (q *Queries) MarkVerificationCodeAsConsumed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markVerificationCodeAsConsumed, id)
	return err
}

const storeVerificationRecord = `-- name: StoreVerificationRecord :exec
INSERT INTO verifications(
  user_id, verification_type, verification_code
) VALUES ($1, $2, $3)
`

type StoreVerificationRecordParams struct {
	UserID           uuid.UUID
	VerificationType interface{}
	VerificationCode string
}

func (q *Queries) StoreVerificationRecord(ctx context.Context, arg StoreVerificationRecordParams) error {
	_, err := q.db.Exec(ctx, storeVerificationRecord, arg.UserID, arg.VerificationType, arg.VerificationCode)
	return err
}
