// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waitlist.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToWaitlist = `-- name: AddToWaitlist :one
INSERT INTO waitlists (
  email,
  source
) VALUES ($1, $2) RETURNING id, email, source, status, created_at
`

type AddToWaitlistParams struct {
	Email  string
	Source pgtype.Text
}

func (q *Queries) AddToWaitlist(ctx context.Context, arg AddToWaitlistParams) (Waitlist, error) {
	row := q.db.QueryRow(ctx, addToWaitlist, arg.Email, arg.Source)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getWaitlistUserByEmail = `-- name: GetWaitlistUserByEmail :one
select id, email, source, status, created_at
from waitlists
where email = $1
limit 1
`

func (q *Queries) GetWaitlistUserByEmail(ctx context.Context, email string) (Waitlist, error) {
	row := q.db.QueryRow(ctx, getWaitlistUserByEmail, email)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listWaitlistUsersByStatus = `-- name: ListWaitlistUsersByStatus :many
select id, email, source, status, created_at
from waitlists
where status = $1
`

func (q *Queries) ListWaitlistUsersByStatus(ctx context.Context, status NullWaitliststatus) ([]Waitlist, error) {
	rows, err := q.db.Query(ctx, listWaitlistUsersByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Waitlist
	for rows.Next() {
		var i Waitlist
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
